# Generated by Django 3.2.9 on 2021-11-24 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggageai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
