# Generated by Django 3.2.9 on 2021-11-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggageai', '0002_items_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
