# Generated by Django 3.2.9 on 2021-11-24 08:41

from django.db import migrations, models
import rest_framework.views


class Migration(migrations.Migration):

    dependencies = [
        ('baggageai', '0005_auto_20211124_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(rest_framework.views.APIView, models.Model),
        ),
        migrations.RemoveField(
            model_name='data',
            name='file',
        ),
    ]
