# Generated by Django 3.2.9 on 2021-11-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggageai', '0006_auto_20211124_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
