version: "3.9"
   
services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    
  frontend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    command: npm run start
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - server
    ports:
      - "3000:3000"
  